In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [47]:
data = pd.read_csv('F:\\Football_datasets\\epl_football_data.csv')

In [48]:
data.head()

Div        Date       HomeTeam   AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
0  E0  16-08-2008        Arsenal  West Brom     1     0   H     1     0   H   
1  E0  16-08-2008         Bolton      Stoke     3     1   H     3     0   H   
2  E0  16-08-2008        Everton  Blackburn     2     3   A     1     1   D   
3  E0  16-08-2008           Hull     Fulham     2     1   H     1     1   D   
4  E0  16-08-2008  Middlesbrough  Tottenham     2     1   H     0     0   D   

   ...   IWA   LBH   LBD   LBA  SBH   SBD    SBA   SJH   SJD    SJA  
0  ...  11.0  1.20  5.00  11.0  1.2  5.50  12.00  1.20  5.50  12.00  
1  ...   4.2  1.73  3.40   4.0  1.8  3.25   4.20  1.80  3.20   4.33  
2  ...   3.3  1.80  3.20   4.0  1.9  3.25   3.75  2.00  3.25   3.40  
3  ...   2.6  2.40  3.25   2.5  2.5  3.20   2.60  2.38  3.20   2.75  
4  ...   2.2  2.80  3.20   2.2  2.8  3.20   2.30  2.88  3.40   2.20  

[5 rows x 44 columns]

In [49]:
data.tail()

Div        Date     HomeTeam      AwayTeam  FTHG  FTAG FTR  HTHG  HTAG  \
4175  E0  12-05-2019    Liverpool        Wolves     2     0   H     1     0   
4176  E0  12-05-2019   Man United       Cardiff     0     2   A     0     1   
4177  E0  12-05-2019  Southampton  Huddersfield     1     1   D     1     0   
4178  E0  12-05-2019    Tottenham       Everton     2     2   D     1     0   
4179  E0  12-05-2019      Watford      West Ham     1     4   A     0     2   

     HTR  ...    IWA   LBH   LBD   LBA   SBH   SBD    SBA   SJH   SJD    SJA  
4175   H  ...  10.54  1.29  5.50  11.0  1.30  5.75  11.50  6.00  5.62  11.50  
4176   A  ...  10.21  1.25  6.50  10.0  1.29  6.25  11.00  6.75  6.18  11.00  
4177   H  ...   7.62  1.40  4.75   8.0  1.40  4.80   8.50  5.15  4.81   8.75  
4178   H  ...   3.64  2.10  3.50   3.5  2.10  3.50   3.70  3.70  3.51   3.80  
4179   A  ...   3.21  2.20  3.70   3.1  2.20  3.75   3.25  3.90  3.73   3.25  

[5 rows x 44 columns]

In [50]:
data.shape

(4180, 44)

In [51]:
data.isnull().sum()

Div         0
Date        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
B365H       0
B365D       0
B365A       0
BWH         1
BWD         1
BWA         1
GBH         2
GBD         2
GBA         2
IWH         1
IWD         1
IWA         1
LBH         1
LBD         1
LBA         1
SBH         0
SBD         0
SBA         0
SJH         0
SJD         0
SJA         0
dtype: int64

In [52]:
data.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'GBH', 'GBD', 'GBA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA',
       'SBH', 'SBD', 'SBA', 'SJH', 'SJD', 'SJA'],
      dtype='object')

In [53]:
data.Referee.value_counts()

M Dean           322
M Atkinson       304
A Marriner       274
L Mason          237
M Oliver         234
A Taylor         226
M Clattenburg    207
K Friend         204
M Jones          202
J Moss           200
P Dowd           188
H Webb           181
L Probert        170
C Foy            160
C Pawson         134
N Swarbrick      132
P Walton          96
S Attwell         94
R East            91
R Madley          91
M Halsey          88
P Tierney         55
A Wiley           54
S Bennett         50
G Scott           50
C Kavanagh        40
R Styles          26
M Riley           23
D Coote           12
S Tanner          11
S Hooper          10
K Stroud           8
Mn Atkinson        2
A Madley           2
l Mason            1
St Bennett         1
Name: Referee, dtype: int64

In [55]:
feature_data = data.iloc[:,:23]
feature_data = feature_data.drop(['Div','Date'],axis=1)

In [57]:
feature_data.head()

HomeTeam   AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR     Referee  HS  \
0        Arsenal  West Brom     1     0   H     1     0   H      H Webb  24   
1         Bolton      Stoke     3     1   H     3     0   H       C Foy  14   
2        Everton  Blackburn     2     3   A     1     1   D  A Marriner  10   
3           Hull     Fulham     2     1   H     1     1   D    P Walton  11   
4  Middlesbrough  Tottenham     2     1   H     0     0   D  M Atkinson  14   

   ...  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR  
0  ...   14    4  11   8   7   5   0   0   0   0  
1  ...    8    2  13  12   4   3   1   2   0   0  
2  ...    5   11  11   9   3   5   2   2   0   0  
3  ...    6    6  10   9   5   6   3   0   0   0  
4  ...   10    5  11  12   7   9   1   2   0   0  

[5 rows x 21 columns]

In [84]:
#Team, Home Goals Scored, Away Goals Scored, Attack Strength, Home Goals Conceded, Away Goals Conceded, Defensive Strength
table = pd.DataFrame(columns=('Team','HGS','AGS','HAS','AAS','HGC','AGC','HDS','ADS',))
table = table[:-10]

In [85]:
feature_data = feature_data[:-10]
feature_data.shape[0]

4170

In [86]:
feature_data_home = feature_data.groupby('HomeTeam')
feature_data_away = feature_data.groupby('AwayTeam')

In [122]:
#list(feature_data_home)[0]
hometeam=list(feature_data_home.HomeTeam)
team=[]
for i in hometeam:
    team.append(i[0])
table.Team = team    

In [123]:
table.HGS = feature_data_home.FTHG.sum().values
table.HGC = feature_data_home.FTAG.sum().values
table.AGS = feature_data_away.FTAG.sum().values
table.AGC = feature_data_away.FTHG.sum().values

In [124]:
num_games = feature_data.shape[0]/20

In [125]:
avg_home_scored = feature_data.FTHG.sum()*1.0 / feature_data.shape[0]
avg_away_scored = feature_data.FTAG.sum()*1.0 / feature_data.shape[0]
avg_home_conceded = avg_away_scored
avg_away_conceded = avg_home_scored

In [126]:
table.HAS = (table.HGS / num_games) / avg_home_scored
table.AAS = (table.AGS / num_games) / avg_away_scored
table.HDS = (table.HGC / num_games) / avg_home_conceded
table.ADS = (table.AGC / num_games) / avg_away_conceded
table.head()

Team  HGS  AGS       HAS       AAS  HGC  AGC       HDS       ADS
0      Arsenal  441  353  1.359642  1.449394  174  291  0.714432  0.897179
1  Aston Villa  179  156  0.551873  0.640526  198  264  0.812975  0.813936
2   Birmingham   38   37  0.117157  0.151920   35   70  0.143708  0.215816
3    Blackburn   98   77  0.302143  0.316157   90  162  0.369534  0.499460
4    Blackpool   30   25  0.092493  0.102648   37   41  0.151920  0.126407

In [127]:
table[table.Team == "Arsenal"]

Team  HGS  AGS       HAS       AAS  HGC  AGC       HDS       ADS
0  Arsenal  441  353  1.359642  1.449394  174  291  0.714432  0.897179

In [136]:
feature_data.columns

Index(['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR',
       'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY',
       'HR', 'AR'],
      dtype='object')

In [263]:
feature_table = feature_data.drop(['FTHG','FTAG','HTHG','HTAG','Referee',],axis=1)
f_HAS = []
f_HDS = []
f_AAS = []
f_ADS = []
for index,row in feature_table.iterrows():
    f_HAS.append(table[table['Team'] == row['HomeTeam']]['HAS'].values[0])
    f_HDS.append(table[table['Team'] == row['HomeTeam']]['HDS'].values[0])
    f_AAS.append(table[table['Team'] == row['AwayTeam']]['AAS'].values[0])
    f_ADS.append(table[table['Team'] == row['AwayTeam']]['ADS'].values[0])
    
feature_table['HAS'] = f_HAS
feature_table['HDS'] = f_HDS
feature_table['AAS'] = f_AAS
feature_table['ADS'] = f_ADS

In [264]:
feature_table.head(20)

HomeTeam       AwayTeam FTR HTR  HS  AS  HST  AST  HF  AF  HC  AC  \
0         Arsenal      West Brom   H   H  24   5   14    4  11   8   7   5   
1          Bolton          Stoke   H   H  14   8    8    2  13  12   4   3   
2         Everton      Blackburn   A   D  10  15    5   11  11   9   3   5   
3            Hull         Fulham   H   D  11  12    6    6  10   9   5   6   
4   Middlesbrough      Tottenham   H   D  14   8   10    5  11  12   7   9   
5      Sunderland      Liverpool   A   D   6  14    3    8  13  12   1   8   
6        West Ham          Wigan   H   H  15  22    8    9  14  11   6  10   
7     Aston Villa       Man City   H   D  14  13   10    8   8  11   7   8   
8         Chelsea     Portsmouth   H   H  18  12   11    8  10   6   8   3   
9      Man United      Newcastle   D   D  18  11   12    4  15  11   6   6   
10      Blackburn           Hull   D   D  12   7    5    4  11  15   6   3   
11         Fulham        Arsenal   H   H   5  15    2    6  14   6   1   5   
12      Liverpool  Middlesbrough   H   D  16   9    8    4  10  12  14   3   
13      Newcastle         Bolton   H   D  10   9    8    4   8  13   4   6   
14          Stoke    Aston Villa   H   H   8   5    2    2  15   5   2   8   
15      Tottenham     Sunderland   A   D  18  12   11    7  12  12  12   6   
16      West Brom        Everton   A   D  14   9    4    7  11  14  11   5   
17       Man City       West Ham   H   D  14   3    9    0  12  16   6   3   
18          Wigan        Chelsea   A   A  10   7    6    3  13  17   7   7   
19     Portsmouth     Man United   A   A  13  12    6    7  11  11   4   3   

    HY  AY  HR  AR       HAS       HDS       AAS       ADS  
0    0   0   0   0  1.359642  0.714432  0.632314  0.838600  
1    1   2   0   0  0.320641  0.472182  0.615890  0.961924  
2    2   2   0   0  1.103746  0.923835  0.316157  0.499460  
3    3   0   0   0  0.329891  0.595360  0.427017  0.665947  
4    1   2   0   0  0.104825  0.176555  1.363170  0.863265  
5    0   2   0   0  0.616618  0.882776  1.408335  0.823185  
6    2   1   0   0  0.832434  1.059331  0.385958  0.548790  
7    0   1   0   0  0.551873  0.812975  1.490454  0.699861  
8    0   1   0   0  1.408972  0.714432  0.090331  0.191152  
9    3   0   0   0  1.341144  0.673373  0.644631  0.900262  
10   0   1   0   0  0.302143  0.369534  0.303839  0.548790  
11   2   0   0   0  0.601202  0.739068  1.449394  0.897179  
12   2   1   0   0  1.347310  0.706220  0.086225  0.206567  
13   1   2   0   0  0.752274  0.923835  0.316157  0.425466  
14   1   0   0   0  0.764606  0.874564  0.640526  0.813936  
15   1   2   0   0  1.153075  0.726750  0.665161  0.909511  
16   3   1   0   0  0.693695  0.985424  0.981318  0.850933  
17   0   2   0   1  1.603206  0.689797  0.817081  0.958841  
18   1   2   0   0  0.326807  0.583042  1.379594  0.684446  
19   2   2   0   0  0.154154  0.250462  1.371382  0.693695

In [265]:
def transformFTResult(row):
    '''Converts results (H,A or D) into numeric values'''
    if(row.FTR == 'H'):
        return 1
    elif(row.FTR == 'A'):
        return -1
    else:
        return 0
    
def transformHTResult(row):
    '''Converts results (H,A or D) into numeric values'''
    if(row.HTR == 'H'):
        return 1
    elif(row.HTR == 'A'):
        return -1
    else:
        return 0    

In [266]:
feature_table["HTResult"] = feature_table.apply(lambda row: transformHTResult(row),axis=1)
feature_table["FTResult"] = feature_table.apply(lambda row: transformFTResult(row),axis=1)

In [267]:
feature_table.head(20)

HomeTeam       AwayTeam FTR HTR  HS  AS  HST  AST  HF  AF  ...  HY  \
0         Arsenal      West Brom   H   H  24   5   14    4  11   8  ...   0   
1          Bolton          Stoke   H   H  14   8    8    2  13  12  ...   1   
2         Everton      Blackburn   A   D  10  15    5   11  11   9  ...   2   
3            Hull         Fulham   H   D  11  12    6    6  10   9  ...   3   
4   Middlesbrough      Tottenham   H   D  14   8   10    5  11  12  ...   1   
5      Sunderland      Liverpool   A   D   6  14    3    8  13  12  ...   0   
6        West Ham          Wigan   H   H  15  22    8    9  14  11  ...   2   
7     Aston Villa       Man City   H   D  14  13   10    8   8  11  ...   0   
8         Chelsea     Portsmouth   H   H  18  12   11    8  10   6  ...   0   
9      Man United      Newcastle   D   D  18  11   12    4  15  11  ...   3   
10      Blackburn           Hull   D   D  12   7    5    4  11  15  ...   0   
11         Fulham        Arsenal   H   H   5  15    2    6  14   6  ...   2   
12      Liverpool  Middlesbrough   H   D  16   9    8    4  10  12  ...   2   
13      Newcastle         Bolton   H   D  10   9    8    4   8  13  ...   1   
14          Stoke    Aston Villa   H   H   8   5    2    2  15   5  ...   1   
15      Tottenham     Sunderland   A   D  18  12   11    7  12  12  ...   1   
16      West Brom        Everton   A   D  14   9    4    7  11  14  ...   3   
17       Man City       West Ham   H   D  14   3    9    0  12  16  ...   0   
18          Wigan        Chelsea   A   A  10   7    6    3  13  17  ...   1   
19     Portsmouth     Man United   A   A  13  12    6    7  11  11  ...   2   

    AY  HR  AR       HAS       HDS       AAS       ADS  HTResult  FTResult  
0    0   0   0  1.359642  0.714432  0.632314  0.838600         1         1  
1    2   0   0  0.320641  0.472182  0.615890  0.961924         1         1  
2    2   0   0  1.103746  0.923835  0.316157  0.499460         0        -1  
3    0   0   0  0.329891  0.595360  0.427017  0.665947         0         1  
4    2   0   0  0.104825  0.176555  1.363170  0.863265         0         1  
5    2   0   0  0.616618  0.882776  1.408335  0.823185         0        -1  
6    1   0   0  0.832434  1.059331  0.385958  0.548790         1         1  
7    1   0   0  0.551873  0.812975  1.490454  0.699861         0         1  
8    1   0   0  1.408972  0.714432  0.090331  0.191152         1         1  
9    0   0   0  1.341144  0.673373  0.644631  0.900262         0         0  
10   1   0   0  0.302143  0.369534  0.303839  0.548790         0         0  
11   0   0   0  0.601202  0.739068  1.449394  0.897179         1         1  
12   1   0   0  1.347310  0.706220  0.086225  0.206567         0         1  
13   2   0   0  0.752274  0.923835  0.316157  0.425466         0         1  
14   0   0   0  0.764606  0.874564  0.640526  0.813936         1         1  
15   2   0   0  1.153075  0.726750  0.665161  0.909511         0        -1  
16   1   0   0  0.693695  0.985424  0.981318  0.850933         0        -1  
17   2   0   1  1.603206  0.689797  0.817081  0.958841         0         1  
18   2   0   0  0.326807  0.583042  1.379594  0.684446        -1        -1  
19   2   0   0  0.154154  0.250462  1.371382  0.693695        -1        -1  

[20 rows x 22 columns]

In [269]:
X = feature_table.drop(['HomeTeam','AwayTeam','FTR','HTR','FTResult'],axis=1)
y = feature_table['FTResult']

In [270]:
X.head()
#y.head()

HS  AS  HST  AST  HF  AF  HC  AC  HY  AY  HR  AR       HAS       HDS  \
0  24   5   14    4  11   8   7   5   0   0   0   0  1.359642  0.714432   
1  14   8    8    2  13  12   4   3   1   2   0   0  0.320641  0.472182   
2  10  15    5   11  11   9   3   5   2   2   0   0  1.103746  0.923835   
3  11  12    6    6  10   9   5   6   3   0   0   0  0.329891  0.595360   
4  14   8   10    5  11  12   7   9   1   2   0   0  0.104825  0.176555   

        AAS       ADS  HTResult  
0  0.632314  0.838600         1  
1  0.615890  0.961924         1  
2  0.316157  0.499460         0  
3  0.427017  0.665947         0  
4  1.363170  0.863265         0

PREDICTION:


In [271]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [272]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


Logistic Regression

In [273]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [274]:
y_pred = classifier.predict(X_test)

In [275]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[217,  17,  57],
       [ 94,  25, 126],
       [ 59,  18, 430]], dtype=int64)

In [276]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.6536914119019366
0.017820440496283063


C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: Futur

KNN

In [277]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [278]:
y_pred = classifier.predict(X_test)

In [279]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[191,  63,  37],
       [ 88,  67,  90],
       [ 83,  85, 339]], dtype=int64)

In [280]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.5897061692186044
0.028282804255967263


SVM

In [281]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [282]:
y_pred = classifier.predict(X_test)

In [283]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[205,  50,  36],
       [ 78,  63, 104],
       [ 47,  47, 413]], dtype=int64)

In [284]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.6632905107504367
0.028834441705457653


KERNAL SVM

In [285]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [286]:
y_pred = classifier.predict(X_test)

In [287]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[207,  39,  45],
       [ 75,  70, 100],
       [ 49,  48, 410]], dtype=int64)

In [288]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Ayush Das\Anaconda3\lib\site-packages\sklearn\svm\base.py:

0.6546284524424443
0.02115573883302184


Naive Bayes

In [289]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [290]:
y_pred = classifier.predict(X_test)

In [291]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[184,  54,  53],
       [ 84,  53, 108],
       [ 69,  38, 400]], dtype=int64)

In [292]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.6213789765706372
0.024802961214480765


Random Forest

In [293]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion = 'entropy', random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [294]:
y_pred = classifier.predict(X_test)

In [295]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[180,  66,  45],
       [ 78,  70,  97],
       [ 56,  81, 370]], dtype=int64)

In [296]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.603483369097653
0.03165030275671508
